"""add phone2 and notification to profile

Revision ID: 1cdb5b91d4e8
Revises: ebc11cd3a8ae
Create Date: 2025-06-11 10:21:39.487464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cdb5b91d4e8'
down_revision: Union[str, None] = 'ebc11cd3a8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallets_id', table_name='wallets')
    op.drop_table('wallets')
    op.create_foreign_key(None, 'devices', 'hubs', ['estate'], ['name'])
    op.add_column('profiles', sa.Column('phone2', sa.String(length=15), nullable=True))
    op.add_column('profiles', sa.Column('notification', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'notification')
    op.drop_column('profiles', 'phone2')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_table('wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_address', sa.VARCHAR(length=66), autoincrement=False, nullable=False),
    sa.Column('private_key', sa.VARCHAR(length=66), autoincrement=False, nullable=False),
    sa.Column('public_key', sa.VARCHAR(length=66), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallets_pkey'),
    sa.UniqueConstraint('account_address', name='wallets_account_address_key')
    )
    op.create_index('ix_wallets_id', 'wallets', ['id'], unique=False)
    # ### end Alembic commands ###
