"""Added token_purchase table

Revision ID: 334ae384eb5b
Revises: 89dbc7fb9ec5
Create Date: 2025-05-14 14:51:58.905335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334ae384eb5b'
down_revision: Union[str, None] = '89dbc7fb9ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('amount_stc', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('strk_used', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_token_purchases_id'), 'token_purchases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_purchases_id'), table_name='token_purchases')
    op.drop_table('token_purchases')
    # ### end Alembic commands ###
