"""Change last_active from DateTime to Integer

Revision ID: 7d70c13569b5
Revises: 1cdb5b91d4e8
Create Date: 2025-06-13 13:32:56.226063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d70c13569b5'
down_revision: Union[str, None] = '1cdb5b91d4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hubs', sa.Column('status', sa.Integer(), nullable=False, server_default="0"))
    op.drop_column('hubs', 'last_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hubs', sa.Column('last_active', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('hubs', 'status')
    # ### end Alembic commands ###
