"""Modified profile

Revision ID: 89dbc7fb9ec5
Revises: 8fcfe6d1978f
Create Date: 2025-05-14 08:03:38.755637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89dbc7fb9ec5'
down_revision: Union[str, None] = '8fcfe6d1978f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('account_address', sa.String(length=66), nullable=False))
    op.create_unique_constraint(None, 'profiles', ['account_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'account_address')
    # ### end Alembic commands ###
