"""Added hubs table

Revision ID: 7bc53494601a
Revises: 25a109c02013
Create Date: 2025-05-17 15:28:57.165592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc53494601a'
down_revision: Union[str, None] = '25a109c02013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_hubs_api_key'), 'hubs', ['api_key'], unique=True)
    op.create_index(op.f('ix_hubs_id'), 'hubs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hubs_id'), table_name='hubs')
    op.drop_index(op.f('ix_hubs_api_key'), table_name='hubs')
    op.drop_table('hubs')
    # ### end Alembic commands ###
