"""Added instruction column to devices table

Revision ID: 567bc6a589f5
Revises: df6fbcce47fa
Create Date: 2025-05-19 18:58:43.740737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567bc6a589f5'
down_revision: Union[str, None] = 'df6fbcce47fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('instruction', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_devices_instruction'), 'devices', ['instruction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_instruction'), table_name='devices')
    op.drop_column('devices', 'instruction')
    # ### end Alembic commands ###
