"""Added account_address field

Revision ID: 74cfd65a77cc
Revises: b569869200a4
Create Date: 2025-05-19 09:14:09.741299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cfd65a77cc'
down_revision: Union[str, None] = 'b569869200a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('account_address', sa.String(length=66), nullable=False))
    op.create_unique_constraint(None, 'devices', ['account_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_column('devices', 'account_address')
    # ### end Alembic commands ###
