"""Remodeled devices & PowerConsumption table

Revision ID: d2abd59e3f48
Revises: 5d8000898cfe
Create Date: 2025-06-13 12:30:03.169674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2abd59e3f48'
down_revision: Union[str, None] = '5d8000898cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('devices', 'instruction',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('devices', 'token_balance',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index('ix_devices_instruction', table_name='devices')
    op.drop_column('devices', 'pin_loads')
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('pin_loads', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_devices_instruction', 'devices', ['instruction'], unique=False)
    op.alter_column('devices', 'token_balance',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('devices', 'instruction',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
