"""add token_balance to devices

Revision ID: df6fbcce47fa
Revises: 74cfd65a77cc
Create Date: 2025-05-19 12:14:34.884424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6fbcce47fa'
down_revision: Union[str, None] = '74cfd65a77cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('token_balance', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'token_balance')
    # ### end Alembic commands ###
